---
- hosts: all
  vars:
    variable1: "PlayBookValue"
  tasks:
    - name: Ping All Servers
      action: ping
    - debug: msg="Hello"
    - name: Execute Shell Commands
      shell: uname
      register: uname_result
    - debug: msg="{{ uname_result }}"